CREATE DATABASE INSURANCE_PROJ;
USE INSURANCE_PROJ;
-- DROP DATABASE INSURANCE_PROJ;
CREATE TABLE CITY
(
	CITY_ID INT PRIMARY KEY AUTO_INCREMENT,
    CITY_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE REGION 
(
	REGION_ID INT PRIMARY KEY AUTO_INCREMENT ,
    CITY_ID INT ,
    REGION_NAME VARCHAR(25) NOT NULL,
    CHECK (REGION_NAME IN ('NORTH','SOUTH','EAST','WEST')),
    FOREIGN KEY(CITY_ID) REFERENCES CITY(CITY_ID)
);


CREATE TABLE INSURANCE_TYPES
(
	TYPE_ID INT PRIMARY KEY AUTO_INCREMENT,
    INSURANCE_NAME VARCHAR(30) NOT NULL,
    CHECK(INSURANCE_NAME IN ('HEALTH_INSURENSE','MOTOR_VECHILE_INSURENSE','TERM_INSURENSE','TRAVEL_INUSURENSE','HOME_INSURENSE'))
);
-- drop table companies;
CREATE TABLE COMPANIES
(
	COMPANY_ID INT PRIMARY KEY AUTO_INCREMENT,
    COMPANY_NAME VARCHAR(100) NOT NUll
    
);
CREATE TABLE COM_BRANCH(
BRANCH_ID INT PRIMARY KEY,
BRANCH_NAME VARCHAR(25) NOT NULL,
COMPANY_ID INT,
REGION_ID INT,
FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(COMPANY_ID), 
FOREIGN KEY (REGION_ID) REFERENCES REGION(REGION_ID) 
 
);

CREATE TABLE CUSTOMER
(
	CUST_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUST_NAME VARCHAR(100) NOT NULL,
    NOMINEE VARCHAR(100),
    NOMINEE_RELATION VARCHAR(50),
    PHN_NO BIGINT NOT NULL,
    ADDRESS VARCHAR(200) NOT NULL,
    DOB DATE NOT NULL
);

-- DROP TABLE INSURANCE_MAIN;

CREATE TABLE INSURANCE_MAIN
(
	POLICY_ID INT PRIMARY KEY AUTO_INCREMENT,
    START_DATE DATE NOT NULL,
	CUST_ID INT,
    COMPANY_ID INT,
    TYPE_ID INT,
    AMT_PREMIUM BIGINT NOT NULL,
    SUM_INSURED BIGINT NOT NULL,
    POLICY_STATUS VARCHAR(30) NOT NULL,
    FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID),
    FOREIGN KEY(COMPANY_ID) REFERENCES COMPANIES(COMPANY_ID),
    FOREIGN KEY(TYPE_ID) REFERENCES INSURANCE_TYPES(TYPE_ID),
    CHECK( AMT_PREMIUM > 200),
    CHECK( SUM_INSURED > 0),
    CHECK( POLICY_STATUS IN ('ACTIVE','INACTIVE'))
);

-- DROP TABLE CLAIM_TXN;

CREATE TABLE CLAIM_TXN
(
	CLAIM_TXN_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    POLICY_ID INT,
    CUST_ID INT,
    CLAIMED_AMT BIGINT NOT NULL,
    CLAIMED_DATE DATE NOT NULL,
	FOREIGN KEY(POLICY_ID) REFERENCES INSURANCE_MAIN(POLICY_ID),
    FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID)
);

