CREATE TABLE COM_BRANCH(
BRANCH_ID INT PRIMARY KEY,
BRANCH_NAME VARCHAR(25) NOT NULL,
COMPANY_ID INT,
REGION_ID INT,
FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(COMPANY_ID), 
FOREIGN KEY (REGION_ID) REFERENCES REGION(REGION_ID) 
 
);


CREATE TABLE BRANCH_DETAILS(
ID INT PRIMARY KEY AUTO_INCREMENT,
BRANCH_NAME VARCHAR(25),
INSURANCE_TYPE_ID INT,
FOREIGN KEY (BRANCH_NAME) REFERENCES COM_BRANCH(BRANCH_NAME),
FOREIGN KEY (INSURANCE_TYPE_ID) REFERENCES INSURANCE_TYPES(TYPE_ID)
);


